// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Identity  string         `gorm:"column:identity" json:"identity"`
	Name      string         `gorm:"column:name;comment:分类id" json:"name"`                  // 分类id
	ParentID  int32          `gorm:"column:parent_id;comment:父级id" json:"parent_id"`        // 父级id
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`      // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:修改时间" json:"updated_at"`      // 修改时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间(软删除)" json:"deleted_at"` // 删除时间(软删除)
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
