// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProblemCategory = "problem_category"

// ProblemCategory mapped from table <problem_category>
type ProblemCategory struct {
	ID         int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProblemID  int32          `gorm:"column:problem_id;not null" json:"problem_id"`
	CategoryID int32          `gorm:"column:category_id;not null" json:"category_id"`
	CreatedAt  time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`      // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;comment:修改时间" json:"updated_at"`      // 修改时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间(软删除)" json:"deleted_at"` // 删除时间(软删除)
}

// TableName ProblemCategory's table name
func (*ProblemCategory) TableName() string {
	return TableNameProblemCategory
}
