// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	problem "github.com/wuqianaer/go-zero-oj/app/cmd/api/internal/handler/problem"
	user "github.com/wuqianaer/go-zero-oj/app/cmd/api/internal/handler/user"
	"github.com/wuqianaer/go-zero-oj/app/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CaptchaThrottling},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/captcha",
					Handler: user.GetCaptchaHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: problem.GetProblemListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/problem"),
	)
}
