// Code generated by goctl. DO NOT EDIT.
package types

type PageReq struct {
	Page  int64 `form:"page"  validate:"number,gte=1"  label:"页数"`
	Limit int64 `form:"limit" validate:"number,gte=1"  label:"条数"`
}

type Pagination struct {
	Page  int64 `json:"page"`
	Limit int64 `json:"limit"`
	Total int64 `json:"total"`
}

type UserLoginReq struct {
	CaptchaCode string `json:"captcha_code"` // 验证码
	UserName    string `json:"username"`     // 用户名
	Password    string `json:"password"`     // 密码
}

type UserLoginResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type UserRegisterReq struct {
	CaptchaCode     string `json:"captcha_code"`     // 验证码
	UserName        string `json:"username"`         // 用户名
	Password        string `json:"password"`         // 密码
	ConfirmPassword string `json:"confirm_password"` // 确认密码
}

type CaptchaResp struct {
	CaptchaID   string `json:"captcha_id"`   // 验证码id
	PictureData string `json:"picture_data"` // 验证码的base64
}

type ProblemPageReq struct {
	Page    int    `form:"page,default=1"`
	Size    int    `form:"size,default=10"`
	KeyWord string `form:"keyword,optional"`
}

type Problem struct {
	ID         int32  `json:"id"`
	Identity   string `json:"identity"`
	Cid        string `json:"cid"`
	Title      string `json:"title"`
	MaxRuntime int32  `json:"max_runtime"`
	MaxMem     int32  `json:"max_mem"`
	Content    string `json:"content"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
	DeletedAt  string `json:"deleted_at"`
}

type ProblemListResp struct {
	Count       int64     `json:"count"`
	ProblemList []Problem `json:"problemList"`
}
